### ISSUE TITLE
Clean up data types for directory data.

### ISSUE THREAD

**Issue by iangow** [mccgr/aus_gov_board#2]
Here are the data:

``` r
library(RPostgreSQL)
#> Loading required package: DBI
library(dplyr, warn.conflicts = FALSE)
pg <- dbConnect(PostgreSQL())
directory <- tbl(pg, sql("SELECT * FROM aus_gov_board.directory"))
directory
#> # Source:   SQL [?? x 81]
#> # Database: postgres 9.6.8 [igow@10.101.13.99:5432/crsp]
#>    abn   acronym acting_canberra_… acting_contact acting_date acting_email
#>    <chr> <chr>   <chr>             <chr>          <chr>       <chr>       
#>  1 <NA>  <NA>    <NA>              <NA>           <NA>        <NA>        
#>  2 <NA>  <NA>    <NA>              <NA>           <NA>        <NA>        
#>  3 <NA>  <NA>    <NA>              <NA>           <NA>        <NA>        
#>  4 <NA>  <NA>    <NA>              <NA>           <NA>        <NA>        
#>  5 <NA>  <NA>    <NA>              <NA>           <NA>        <NA>        
#>  6 <NA>  <NA>    <NA>              <NA>           <NA>        <NA>        
#>  7 <NA>  <NA>    <NA>              <NA>           <NA>        <NA>        
#>  8 <NA>  <NA>    <NA>              <NA>           <NA>        <NA>        
#>  9 <NA>  <NA>    <NA>              <NA>           <NA>        <NA>        
#> 10 <NA>  <NA>    <NA>              <NA>           <NA>        <NA>        
#> # ... with more rows, and 75 more variables: acting_fax <chr>,
#> #   acting_location_address <chr>, acting_mobile_number <chr>,
#> #   acting_phone_number <chr>, acting_postal_address <chr>,
#> #   acting_website <chr>, administrative_area <chr>,
#> #   annual_report_prep_tabled <chr>, annual_reports <chr>, asl <chr>,
#> #   auditor <chr>, auditor_other <chr>,
#> #   board_committee_appointed_by <chr>,
#> #   board_committee_appointed_by_more <chr>, board_contact_email <chr>,
#> #   board_function_category <chr>, budget_documentation <chr>,
#> #   canberra_fax <chr>, canberra_phone <chr>, classification <chr>,
#> #   contact <chr>, content_id <chr>, country <chr>, creation_date <chr>,
#> #   current_budget_total_appropriations <chr>,
#> #   current_budget_total_expenditure <chr>, decisions <chr>,
#> #   description <chr>, email <chr>, end_date <chr>,
#> #   established_by_under <chr>, established_by_under_more <chr>,
#> #   fax_number <chr>, first_name <chr>, gfs_function <chr>,
#> #   gfs_sector_classification <chr>, honorific <chr>, hours <chr>,
#> #   importance <chr>, is_acting_current <chr>,
#> #   is_portfolio_department <chr>, item <chr>, last_name <chr>,
#> #   locality <chr>, location_address <chr>, materiality <chr>,
#> #   max_members <chr>, media_releases <chr>, mobile_number <chr>,
#> #   org_acronym <chr>, overseas_enquiries <chr>, paid_members <chr>,
#> #   parent_board_non_board <chr>, parent_directory_structure <chr>,
#> #   parent_non_portfolio <chr>, parent_organisation <chr>,
#> #   personal_title <chr>, phone_number <chr>, portfolio <chr>,
#> #   postal_address <chr>, postal_code <chr>, ps_act_body <chr>,
#> #   role_belongs_to <chr>, salutation <chr>,
#> #   secretariat_provided_by_portfolio <chr>, start_date <chr>,
#> #   strat_corp_org_plan <chr>, thoroughfare <chr>, title <chr>,
#> #   tty_number <chr>, type <chr>, type_of_body <chr>,
#> #   unique_record_id <chr>, updated <chr>, website <chr>
rs <- dbDisconnect(pg)
```

Created on 2018-03-22 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

We might want to move some of the fields around. For example, this code will move `unique_record_id` and `type_of_body` to be the first two fields in the table. Modifications should occur in `get_directory.py` (so I just realised that the example below [R code] isn't too helpful … but something similar can be done with Pandas before pushing data to PostgreSQL).

```r
df <- 
    df %>% 
    select(unique_record_id, type_of_body, everything())
```

**Comment by bdcallen** [comment]
@iangow I've had Jupyter Notebook running successfully on my system, and I've been playing around with the part of the code in get_directly.py which solely scrapes the data and puts it into a Pandas dataframe. I had a look at the data and counted the number of missing values in each column. Most columns have a large percentage of NA's, but there are a number of columns which have no missing values. I was thinking of ordering the columns by the number of NA's in ascending order (which I've worked out how to do). Or is there some other basis by which we should order the columns?

**Comment by iangow** [comment]
I wouldn't worry too much about the order of most variables, as this is easy to fix downstream. I think the main thing would be to put the natural "primary key" variables first. So `unique_record_id` might be the only one to worry about.

The main thing is probably to flag any variables that should be dates, numbers, or timestamps and make sure they are converted as such before being pushed to the database.

**Comment by iangow** [comment]
> I've also checked which columns are numeric, and found that all non-null entries for each one were integers, though I am having problems casting all of them to `int64` since Python treats `np.nan` as being of type `float`. I'm guessing the way to get around this within the program is to use the `CAST` function when writing the data into the SQL table. I also spotted a couple of columns which naturally should be booleans, but noted that typecasting to bool in Python converts `np.nan` to `True`!

I think the best (long-term) approach would be to sort this out in Pandas. This might require a little digging (StackOverflow, etc.). But if stuck, we could try server-side fixes (i.e., `CAST`) instead.
